const products = [{
        id: 1,
        name: "Wireless Headphones",
        price: 15000,
        description: "BERIBES Bluetooth Headphones Over Ear, 65H Playtime and 6 EQ Music Modes Wireless Headphones with Microphone, HiFi Stereo Foldable Lightweight Headsets, Deep Bass for Home Office Cellphone PC",
        description2: "🔥<strong>Optional 6 music modes:</strong> Adopted most advanced dual 40mm dynamic sound unit and 6 EQ modes, BERIBES updated headphones wireless bluetooth black were born for audiophiles. Simply switch the headphone between balanced sound, extra powerful bass and mid treble enhancement modes. No matter you prefer rock, Jazz, Rhythm & Blues or classic music, BERIBES has always been committed to providing our customers with better sound quality as the focal point of our engineering.<br>🔥<strong>65 Hours Playtime:</strong> Low power consumption technology applied, BERIBES bluetooth headphones with built-in 500mAh battery can continually play more than 65 hours, standby more than 950 hours after one fully charge. By included 3.5mm audio cable, the wireless headphones over ear can be easily switched to wired mode when powers off. No power shortage problem anymore <br>🔥<strong>All Day Comfort</strong>: Made by premium materials, 0.38lb BERIBES over the ear headphones wireless bluetooth for work are the most lightweight headphones in the market. Adjustable headband makes it easy to fit all sizes heads without pains. Softer and more comfortable memory protein earmuffs protect your ear in long term using<br>🔥<strong>Latest Bluetooth 5.3 and Microphone:</strong> Carrying latest Bluetooth 5.3 chip, after booting, 1-3 seconds to quickly pair bluetooth. Beribes bluetooth headphones with microphone has faster and more stable transmitter range up to 33ft. Two smart devices can be connected to Beribes over-ear headphones at the same time, makes you able to pick up a call from your phone when watching movie on your pad without switching<br>🔥<strong>After Sale Protection:</strong> Package include a Foldable Deep Bass Headphone,3.5mm backup audio cable, USB charging cable and User Manual. Provide a 30-day return and 12-month warranty, lifetime worry free user support, contact us anytime if you have any questions about the product, we will reply within 10 hours",
        image: "headphones.jpg"
    },
    {
        id: 2,
        name: "Smartwatch",
        price: 100000,
        description: "Smart Watch with Alexa Built-in, 1.83' HD Touchscreen,Digital Bluetooth Calling, IP68 Waterproof Fitness Tracker, 120+ Sports Modes, 24/7 Heart Rate/Sleep Monitor for iPhone Android",
        description2: "<strong>Alexa Built-In & Hands-Free Convenience:</strong> Smart watch with built-in Alexa voice assistant, control music, set reminders, check weather, and access over 6M Alexa skills directly from your wrists, life just got easier <br><br><strong>Bluetooth Calls:</strong> Smart watch for men women is powered by Bluetooth 5.3 chip Provides you with a stable connection, make or answer calls directly through the watch’s, ideal for workouts, driving, or busy days<br><br><strong>1.83 HD Screen:</strong> Fitness tracking watch with HD screen, enjoy vivid colors and sharp details on the ultra - large touchscreen, even under sunlight, with customizable watch faces <br><br><strong>120 + Sports Modes:</strong> Sports watch from running, cycling, swimming to yoga, monitor real - time stats(calories, distance, duration) for all activities <br><br><strong>24 / 7 Health Monitoring: </strong>Fitness watch with advanced sensors track heart rate, Steps, calories, sleep quality, and stress levels, providing actionable insights for better wellness(not intended for medical diagnosis)<br><br><strong>IP68 Waterproof:</strong> Smartwatch has IP68 waterproof rating, swim, shower, or train in heavy rain worry - free;withstands submersion up to 1.5 meters for 30 minutes（ Note: High water temperatures can affect water resistance）<br><br><strong>iOS & Android Compatibility:</strong> Sync effortlessly with iPhone and Android phones(iOS 10.0 + /Android 6.0+), receive notifications for calls, texts, and apps (Note: Compatible with message notifications but does not support replies)",
        image: "smartwatch.jpg"
    },
    {
        id: 3,
        name: "Bluetooth Speaker",
        price: 12000,
        description: "Portable Bluetooth Speaker with Lights, Powerful Crystal Clear Sound, IPX5 Waterproof, All Day Playtime, AUX&TF-Card Input, Bluetooth 5.3, TWS Paring, Small Wireless Speaker for Outdoor, Gift Ideas",
        description2: "Engineered with premium craftsmanship, this portable speaker features a space-saving form measuring a mere 2.99 inches (7.6 cm) in width and length, and 4.25 inches (10.8 cm) in height. Ultra-lightweight at just 0.582 lbs (264g), it slips effortlessly into any bag. Driven by a robust 20W peak power, it delivers immersive audio with punchy bass and crisp highs, while its 15W continuous output ensures crystal-clear sound for indoor relaxation or outdoor adventures<br><br><strong>Immersive Sound</strong>: Experience stunning 15W（20W peak) sound in a compact design ( Pro Tip: For larger spaces, pair two speakers in stereo mode (30W total) for immersive sound). With zero distortion audio, this Bluetooth speaker delivers loud highs, crisp midrange, and full bass for an immersive listening experience. With up to 15 hours of playtime on a single charge, enjoy your favorite tunes all day and night without interruption<br><br><strong>Portable Design</strong>: Compact and lightweight at 4.25 inches high and 2.99 inches in diameter, this speaker is perfect for on-the-go use. It features a TF card slot (supports WAV / FLAC / APE / MP3 formats), a 3.5mm AUX input port, Type-C fast charging, and a lanyard for convenient carrying<br><br><strong>Dynamic Beat-Synced Light Show</strong>: Enjoy an exciting light show that dances to the rhythm of your music. With vibrant LED that sync with the beat, this speaker adds an extra dimension to your listening experience<br><br><strong>360° Stereo Pairing</strong>: Enjoy true wireless stereo sound by pairing two speakers together. With 360° coverage, you can enjoy loud 30W music in any setting, whether it's at home, parties, the beach, park, or elsewhere<br><br><strong>Advanced Bluetooth 5.3</strong>: Equipped with the latest Bluetooth 5.3 chip, this speaker ensures fast pairing and a stable connection.",
        image: "speaker.jpg"
    },
    {
        id: 4,
        name: "Laptop Backpack",
        price: 8500,
        description: "Laptop Backpack,Business Travel Anti Theft Slim Durable Laptops Backpack with USB Charging Port,Water Resistant College Computer Bag for Women & Men Fits 15.6 Inch Laptop and Notebook",
        description2: "<strong>Storage Space & Pockets:</strong> One separate laptop compartment hold 15.6 Inch Laptop as well as 15 Inch,14 Inch and 13 Inch Macbook/Laptop.One spacious packing compartment roomy for iPad,mouse, charger, binders, clothes, etc. Mesh pockets at side for water bottle and compact umbrella make your items organized and easier to find.<br><strong>COMFY&STURDY:</strong> Comfortable airflow back design with thick but soft multi-panel ventilated padding, gives you maximum back support. Breathable and adjustable shoulder straps relieve the stress of shoulder. Foam padded top handle for a long time carry on<br><strong>FUNCTIONAL & SAFE:</strong> A luggage strap allows backpack fit on luggage / suitcase, slide over the luggage upright handle tube for easier carrying. With a hidden anti theft pocket on the back protect your valuable items from thieves.making your journey and travelling more convenient wherever you go.<br><strong>USB PORT DESIGN:</strong> With built in USB charger outside and built in charging cable inside, this usb backpack offers you a more convenient way to charge your phone while walking.Headphone Jack: you can listen to your favorite music on the go hands - free. <br><strong>DURABLE MATERIAL & SOLID:</strong> Made of Water Resistant and Durable Polyester Fabric with metal zippers.Ensure a secure & long - lasting usage everyday & weekend.Serve you well as professional office work bag, slim USB charging bagpack,perfects for business traveling, weekend getaways, shopping & outdoor activities in daily life.Good Gift for college.",
        image: "backpack.jpg"
    },
    {
        id: 5,
        name: "Dehumidifier",
        price: 60000,
        description: "Dehumidifier,95OZ Dehumidifier for Home 1000 Sq.Ft - Quiet with Auto Shut Off & Relaxing 7 Color Ambient Light,Ideal for Livingroom, Bedroom, Basement(Black)",
        description2: "Semiconductor dehumidifiers use thermoelectric cooling to remove moisture from the air. They create a drier, more comfortable environment by reducing humidity and improving air quality. <br><br>Our home dehumidifier features intelligent auto-shutoff, automatically powering down when the water tank is full. Set it and forget it, knowing your dehumidifier is working efficiently and safely, giving you true peace of mind. <br><br>Our dehumidifier features a captivating 7-color ambient light, allowing you to bathe your room in a spectrum of soothing hues. Choose from a calming blue, energizing green, romantic red, and more – easily select the perfect color to create your desired atmosphere and enhance your living space. Dehumidify in style and set the perfect mood, every time. <br><br>Sleep Mode creates the perfect sleep sanctuary. The dehumidifier's atmosphere lights automatically turn off, and noise fades to a whisper. Experience truly undisturbed dehumidification for a night of perfect rest. <br><br>Elevate your home's comfort and style with our sleek and compact dehumidifier. Designed to seamlessly blend into any space, from the living room and bedroom to the bathroom, basement, and even your RV. Its modern aesthetics and space-saving footprint make it the perfect dehumidification solution for every corner of your home.",
        image: "demodifier.jpg"
    },
    {
        id: 6,
        name: "Camera lens",
        price: 15000,
        description: "Tamron 18-300mm F/3.5-6.3 Di III-A VC VXD Lens for Sony E APS-C Mirrorless Cameras",
        description2: "- World’s first 16.6x all-in-one zoom lens for APS-C mirrorless cameras <br><br>- Best-in-class, extremely fast and precise AF provided by VXD linear motor focus mechanism <br><br>- Maintains high resolving power from the center to the corners throughout the range<br><br>- Compact and portable design at 4.9 inches and a weight of just 21.9 ounces<br><br>- Moisture-Resistant Construction and Fluorine Coating",
        image: "lens.jpg"
    }
];